/// <reference types="vite-plugin-pwa/client" />
import { registerSW } from 'virtual:pwa-register'

/**
 * Register the service worker generated by vite-plugin-pwa.
 * With `registerType: 'autoUpdate'`, new SW versions activate automatically.
 * Safe to call once on app startup.
 */
export function registerServiceWorker() {
  if (typeof window === 'undefined' || !('serviceWorker' in navigator)) return
  return registerSW({ immediate: true })
}

/**
 * True when the app is running as an installed PWA (standalone display mode).
 * Falls back to the iOS Safari `navigator.standalone` flag.
 */
export function isPWA(): boolean {
  if (typeof window === 'undefined') return false
  const standalone = window.matchMedia('(display-mode: standalone)').matches
  const iosStandalone = (window.navigator as { standalone?: boolean }).standalone === true
  return standalone || iosStandalone
}

// Notification helpers live in ./notifications.ts — re-export so callers can
// import everything PWA-related from one place without touching that file.
export {
  requestNotificationPermission,
  isNotificationsEnabled,
  scheduleMealReminders,
} from './notifications'
