import React, { createContext, useContext, useState } from 'react'

export const LANGUAGES = [
  { code: 'en', label: 'English' },
  { code: 'es', label: 'Español' },
  { code: 'fr', label: 'Français' },
  { code: 'de', label: 'Deutsch' },
  { code: 'hi', label: 'हिन्दी' },
  { code: 'ur', label: 'اردو' },
  { code: 'ar', label: 'العربية' },
  { code: 'zh', label: '中文' },
  { code: 'ja', label: '日本語' },
  { code: 'pt', label: 'Português' },
  { code: 'ko', label: '한국어' },
  { code: 'tr', label: 'Türkçe' },
  { code: 'ru', label: 'Русский' },
  { code: 'it', label: 'Italiano' },
  { code: 'nl', label: 'Nederlands' },
  { code: 'pl', label: 'Polski' },
  { code: 'sv', label: 'Svenska' },
  { code: 'th', label: 'ไทย' },
  { code: 'vi', label: 'Tiếng Việt' },
  { code: 'id', label: 'Bahasa Indonesia' },
  { code: 'ms', label: 'Bahasa Melayu' },
  { code: 'bn', label: 'বাংলা' },
  { code: 'ta', label: 'தமிழ்' },
  { code: 'fil', label: 'Filipino' },
  { code: 'fa', label: 'فارسی' },
] as const

export type LangCode = typeof LANGUAGES[number]['code']

const translations: Record<string, Record<string, string>> = {
  en: {
    'home.greeting.morning': 'Good morning',
    'home.greeting.afternoon': 'Good afternoon',
    'home.greeting.evening': 'Good evening',
    'home.todaysIntake': "Today's Intake",
    'home.goal': 'Goal',
    'home.remaining': 'Remaining',
    'nav.today': 'Today',
    'nav.nutrition': 'Nutrition',
    'nav.sleep': 'Sleep',
    'nav.mood': 'Mood',
    'coach.title': 'Sage',
    'coach.placeholder': 'Ask Sage anything…',
    'mood.title': 'Mood',
    'mood.question': 'How are you, really?',
    'sleep.title': 'Sleep',
    'settings.title': 'Profile',
    'settings.signOut': 'Sign Out',
    'settings.language': 'Language',
    'settings.theme': 'Theme',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.loading': 'Loading…',
  },
  es: {
    'home.greeting.morning': 'Buenos días',
    'home.greeting.afternoon': 'Buenas tardes',
    'home.greeting.evening': 'Buenas noches',
    'home.todaysIntake': 'Consumo de hoy',
    'home.goal': 'Objetivo',
    'home.remaining': 'Restante',
    'nav.today': 'Hoy',
    'nav.nutrition': 'Nutrición',
    'nav.sleep': 'Sueño',
    'nav.mood': 'Ánimo',
    'coach.title': 'Sage',
    'coach.placeholder': 'Pregúntale a Sage…',
    'mood.title': 'Ánimo',
    'mood.question': '¿Cómo estás, de verdad?',
    'sleep.title': 'Sueño',
    'settings.title': 'Perfil',
    'settings.signOut': 'Cerrar sesión',
    'settings.language': 'Idioma',
    'settings.theme': 'Tema',
    'common.save': 'Guardar',
    'common.cancel': 'Cancelar',
    'common.loading': 'Cargando…',
  },
  fr: {
    'home.greeting.morning': 'Bonjour',
    'home.greeting.afternoon': 'Bon après-midi',
    'home.greeting.evening': 'Bonsoir',
    'home.todaysIntake': "Apports d'aujourd'hui",
    'home.goal': 'Objectif',
    'home.remaining': 'Restant',
    'nav.today': "Aujourd'hui",
    'nav.nutrition': 'Nutrition',
    'nav.sleep': 'Sommeil',
    'nav.mood': 'Humeur',
    'coach.title': 'Sage',
    'coach.placeholder': 'Demandez à Sage…',
    'mood.title': 'Humeur',
    'mood.question': 'Comment allez-vous, vraiment ?',
    'sleep.title': 'Sommeil',
    'settings.title': 'Profil',
    'settings.signOut': 'Déconnexion',
    'settings.language': 'Langue',
    'settings.theme': 'Thème',
    'common.save': 'Enregistrer',
    'common.cancel': 'Annuler',
    'common.loading': 'Chargement…',
  },
  de: {
    'home.greeting.morning': 'Guten Morgen',
    'home.greeting.afternoon': 'Guten Tag',
    'home.greeting.evening': 'Guten Abend',
    'home.todaysIntake': 'Heutige Aufnahme',
    'home.goal': 'Ziel',
    'home.remaining': 'Verbleibend',
    'nav.today': 'Heute',
    'nav.nutrition': 'Ernährung',
    'nav.sleep': 'Schlaf',
    'nav.mood': 'Stimmung',
    'coach.title': 'Sage',
    'coach.placeholder': 'Frag Sage etwas…',
    'mood.title': 'Stimmung',
    'mood.question': 'Wie geht es dir wirklich?',
    'sleep.title': 'Schlaf',
    'settings.title': 'Profil',
    'settings.signOut': 'Abmelden',
    'settings.language': 'Sprache',
    'settings.theme': 'Design',
    'common.save': 'Speichern',
    'common.cancel': 'Abbrechen',
    'common.loading': 'Laden…',
  },
  ar: {
    'home.greeting.morning': 'صباح الخير',
    'home.greeting.afternoon': 'مساء الخير',
    'home.greeting.evening': 'مساء الخير',
    'home.todaysIntake': 'استهلاك اليوم',
    'home.goal': 'الهدف',
    'home.remaining': 'المتبقي',
    'nav.today': 'اليوم',
    'nav.nutrition': 'التغذية',
    'nav.sleep': 'النوم',
    'nav.mood': 'المزاج',
    'coach.title': 'سيج',
    'coach.placeholder': 'اسأل سيج أي شيء…',
    'mood.title': 'المزاج',
    'mood.question': 'كيف حالك حقًا؟',
    'sleep.title': 'النوم',
    'settings.title': 'الملف الشخصي',
    'settings.signOut': 'تسجيل الخروج',
    'settings.language': 'اللغة',
    'settings.theme': 'المظهر',
    'common.save': 'حفظ',
    'common.cancel': 'إلغاء',
    'common.loading': 'جارٍ التحميل…',
  },
  hi: {
    'home.greeting.morning': 'सुप्रभात',
    'home.greeting.afternoon': 'नमस्कार',
    'home.greeting.evening': 'शुभ संध्या',
    'home.todaysIntake': 'आज का सेवन',
    'home.goal': 'लक्ष्य',
    'home.remaining': 'शेष',
    'nav.today': 'आज',
    'nav.nutrition': 'पोषण',
    'nav.sleep': 'नींद',
    'nav.mood': 'मनोदशा',
    'coach.title': 'सेज',
    'coach.placeholder': 'सेज से कुछ भी पूछें…',
    'mood.title': 'मनोदशा',
    'mood.question': 'आप वास्तव में कैसे हैं?',
    'sleep.title': 'नींद',
    'settings.title': 'प्रोफ़ाइल',
    'settings.signOut': 'साइन आउट',
    'settings.language': 'भाषा',
    'settings.theme': 'थीम',
    'common.save': 'सहेजें',
    'common.cancel': 'रद्द करें',
    'common.loading': 'लोड हो रहा है…',
  },
  ur: {
    'home.greeting.morning': 'صبح بخیر',
    'home.greeting.afternoon': 'سہ پہر بخیر',
    'home.greeting.evening': 'شام بخیر',
    'home.todaysIntake': 'آج کی خوراک',
    'home.goal': 'ہدف',
    'home.remaining': 'باقی',
    'nav.today': 'آج',
    'nav.nutrition': 'غذائیت',
    'nav.sleep': 'نیند',
    'nav.mood': 'موڈ',
    'coach.title': 'سیج',
    'coach.placeholder': 'سیج سے کچھ بھی پوچھیں…',
    'mood.title': 'موڈ',
    'mood.question': 'آپ واقعی کیسے ہیں؟',
    'sleep.title': 'نیند',
    'settings.title': 'پروفائل',
    'settings.signOut': 'سائن آؤٹ',
    'settings.language': 'زبان',
    'settings.theme': 'تھیم',
    'common.save': 'محفوظ کریں',
    'common.cancel': 'منسوخ کریں',
    'common.loading': 'لوڈ ہو رہا ہے…',
  },
  zh: {
    'home.greeting.morning': '早上好',
    'home.greeting.afternoon': '下午好',
    'home.greeting.evening': '晚上好',
    'home.todaysIntake': '今日摄入',
    'home.goal': '目标',
    'home.remaining': '剩余',
    'nav.today': '今天',
    'nav.nutrition': '营养',
    'nav.sleep': '睡眠',
    'nav.mood': '心情',
    'coach.title': 'Sage',
    'coach.placeholder': '向 Sage 提问…',
    'mood.title': '心情',
    'mood.question': '你真的还好吗？',
    'sleep.title': '睡眠',
    'settings.title': '个人资料',
    'settings.signOut': '退出登录',
    'settings.language': '语言',
    'settings.theme': '主题',
    'common.save': '保存',
    'common.cancel': '取消',
    'common.loading': '加载中…',
  },
  pt: {
    'home.greeting.morning': 'Bom dia',
    'home.greeting.afternoon': 'Boa tarde',
    'home.greeting.evening': 'Boa noite',
    'home.todaysIntake': 'Consumo de hoje',
    'home.goal': 'Meta',
    'home.remaining': 'Restante',
    'nav.today': 'Hoje',
    'nav.nutrition': 'Nutrição',
    'nav.sleep': 'Sono',
    'nav.mood': 'Humor',
    'coach.title': 'Sage',
    'coach.placeholder': 'Pergunte algo ao Sage…',
    'mood.title': 'Humor',
    'mood.question': 'Como você está, de verdade?',
    'sleep.title': 'Sono',
    'settings.title': 'Perfil',
    'settings.signOut': 'Sair',
    'settings.language': 'Idioma',
    'settings.theme': 'Tema',
    'common.save': 'Salvar',
    'common.cancel': 'Cancelar',
    'common.loading': 'Carregando…',
  },
}

interface LanguageContextValue {
  lang: LangCode
  setLang: (l: LangCode) => void
  t: (key: string) => string
}

const LanguageContext = createContext<LanguageContextValue | null>(null)

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [lang, setLangState] = useState<LangCode>(() => (localStorage.getItem('lang') as LangCode) || 'en')
  const setLang = (l: LangCode) => { localStorage.setItem('lang', l); setLangState(l) }
  const t = (key: string): string => {
    return translations[lang]?.[key] ?? translations.en?.[key] ?? key
  }
  return <LanguageContext.Provider value={{ lang, setLang, t }}>{children}</LanguageContext.Provider>
}

export function useLanguage(): LanguageContextValue {
  const ctx = useContext(LanguageContext)
  if (!ctx) throw new Error('useLanguage must be used within LanguageProvider')
  return ctx
}
