import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = string;

interface Translations {
  [key: string]: {
    [lang: string]: string;
  };
}

const translations: Translations = {
  home: { 
    English: 'Home', Español: 'Inicio', Français: 'Accueil', Deutsch: 'Startseite', हिन्दी: 'होम', اردو: 'ہوم', العربية: 'الرئيسية', 中文: '首页', 日本語: 'ホーム', Português: 'Início', 한국어: '홈', Türkçe: 'Ana Sayfa', Русский: 'Главная', Italiano: 'Home', Nederlands: 'Home', Polski: 'Główna', Svenska: 'Hem', ไทย: 'หน้าแรก', 'Tiếng Việt': 'Trang chủ', 'Bahasa Indonesia': 'Beranda', 'Bahasa Melayu': 'Utama', বাংলা: 'হোম', தமிழ்: 'முகப்பு', Filipino: 'Home' 
  },
  logs: { 
    English: 'Logs', Español: 'Registros', Français: 'Journaux', Deutsch: 'Protokolle', हिन्दी: 'लॉग', اردو: 'لاگز', العربية: 'السجلات', 中文: '日志', 日本語: 'ログ', Português: 'Registos', 한국어: '로그', Türkçe: 'Günlükler', Русский: 'Журналы', Italiano: 'Log', Nederlands: 'Logboeken', Polski: 'Logi', Svenska: 'Loggar', ไทย: 'บันทึก', 'Tiếng Việt': 'Nhật ký', 'Bahasa Indonesia': 'Log', 'Bahasa Melayu': 'Log', বাংলা: 'লগ', தமிழ்: 'பதிவுகள்', Filipino: 'Mga Log' 
  },
  coach: { 
    English: 'Coach', Español: 'Entrenador', Français: 'Entraîneur', Deutsch: 'Coach', हिन्दी: 'कोच', اردو: 'کوچ', العربية: 'مدرب', 中文: '教练', 日本語: 'コーチ', Português: 'Treinador', 한국어: '코치', Türkçe: 'Koç', Русский: 'Тренер', Italiano: 'Coach', Nederlands: 'Coach', Polski: 'Trener', Svenska: 'Coach', ไทย: 'โค้ช', 'Tiếng Việt': 'Huấn luyện viên', 'Bahasa Indonesia': 'Pelatih', 'Bahasa Melayu': 'Pelatih', বাংলা: 'কোচ', தமிழ்: 'பயிற்சியாளர்', Filipino: 'Coach' 
  },
  plans: { 
    English: 'Plans', Español: 'Planes', Français: 'Plans', Deutsch: 'Pläne', हिन्दी: 'योजनाएं', اردو: 'منصوبے', العربية: 'خطط', 中文: '计划', 日本語: 'プラン', Português: 'Planos', 한국어: '계획', Türkçe: 'Planlar', Русский: 'Планы', Italiano: 'Piani', Nederlands: 'Plannen', Polski: 'Plany', Svenska: 'Planer', ไทย: 'แผน', 'Tiếng Việt': 'Kế hoạch', 'Bahasa Indonesia': 'Rencana', 'Bahasa Melayu': 'Rancangan', বাংলা: 'পরিকল্পনা', தமிழ்: 'திட்டங்கள்', Filipino: 'Mga Plano' 
  },
  insights: { 
    English: 'Insights', Español: 'Información', Français: 'Aperçus', Deutsch: 'Einblicke', हिन्दी: 'इनसाइट्स', اردو: 'بصیرت', العربية: 'بصيرة', 中文: '见解', 日本語: 'インサイト', Português: 'Insights', 한국어: '통찰', Türkçe: 'Analizler', Русский: 'Инсайты', Italiano: 'Approfondimenti', Nederlands: 'Inzichten', Polski: 'Wnioski', Svenska: 'Insikter', ไทย: 'ข้อมูลเชิงลึก', 'Tiếng Việt': 'Thông tin chi tiết', 'Bahasa Indonesia': 'Wawasan', 'Bahasa Melayu': 'Wawasan', বাংলা: 'ইনসাইট', தமிழ்: 'அறிதல்கள்', Filipino: 'Mga Insight' 
  },
  goodMorning: { 
    English: 'Good Morning', Español: 'Buen día', Français: 'Bonjour', Deutsch: 'Guten Morgen', हिन्दी: 'सुप्रभात', اردو: 'صبح بخیر', العربية: 'صباح الخير', 中文: '早上好', 日本語: 'おはようございます', Português: 'Bom dia', 한국어: '좋은 아침', Türkçe: 'Günaydın', Русский: 'Доброе утро', Italiano: 'Buongiorno', Nederlands: 'Goedemorgen', Polski: 'Dzień dobry', Svenska: 'God morgon', ไทย: 'อรุณสวัสดิ์', 'Tiếng Việt': 'Chào buổi sáng', 'Bahasa Indonesia': 'Selamat Pagi', 'Bahasa Melayu': 'Selamat Pagi', বাংলা: 'সুপ্রভাত', தமிழ்: 'காலை வணக்கம்', Filipino: 'Magandang Umaga' 
  },
  goodAfternoon: { 
    English: 'Good Afternoon', Español: 'Buenas tardes', Français: 'Bon après-midi', Deutsch: 'Guten Tag', हिन्दी: 'शुभ दोपहर', اردو: 'دوپہر بخیر', العربية: 'مساء الخير', 中文: '下午好', 日本語: 'こんにちは', Português: 'Boa tarde', 한국어: '좋은 오후', Türkçe: 'Tünaydın', Русский: 'Добрый день', Italiano: 'Buon pomeriggio', Nederlands: 'Goedemiddag', Polski: 'Dzień dobry', Svenska: 'God middag', ไทย: 'สวัสดียามบ่าย', 'Tiếng Việt': 'Chào buổi chiều', 'Bahasa Indonesia': 'Selamat Siang', 'Bahasa Melayu': 'Selamat Tengahari', বাংলা: 'শুভ দুপুর', தமிழ்: 'மதிய வணக்கம்', Filipino: 'Magandang Hapon' 
  },
  goodEvening: { 
    English: 'Good Evening', Español: 'Buenas noches', Français: 'Bonsoir', Deutsch: 'Guten Abend', हिन्दी: 'शुभ संध्या', اردو: 'شام بخیر', العربية: 'مساء الخير', 中文: '晚上好', 日本語: 'こんばんは', Português: 'Boa noite', 한국어: '좋은 저녁', Türkçe: 'İyi Akşamlar', Русский: 'Добрый вечер', Italiano: 'Buonasera', Nederlands: 'Goedenavond', Polski: 'Dobry wieczór', Svenska: 'God kväll', ไทย: 'สวัสดียามเย็น', 'Tiếng Việt': 'Chào buổi tối', 'Bahasa Indonesia': 'Selamat Malam', 'Bahasa Melayu': 'Selamat Petang', বাংলা: 'শুভ সন্ধ্যা', தமிழ்: 'மாலை வணக்கம்', Filipino: 'Magandang Gabi' 
  },
  dailyProgress: { 
    English: 'Daily Progress', Español: 'Progreso diario', Français: 'Progrès quotidien', Deutsch: 'Täglicher Fortschritt', हिन्दी: 'दैनिक प्रगति', اردو: 'روزانہ کی ترقی', العربية: 'التقدم اليومي', 中文: '今日进度', 日本語: '今日の進捗', Português: 'Progresso Diário', 한국어: '일일 진행 상황', Türkçe: 'Günlük İlerleme', Русский: 'Дневной прогресс', Italiano: 'Progressi giornalieri', Nederlands: 'Dagelijkse voortgang', Polski: 'Dzienny postęp', Svenska: 'Dagliga framsteg', ไทย: 'ความคืบหน้ารายวัน', 'Tiếng Việt': 'Tiến độ hàng ngày', 'Bahasa Indonesia': 'Kemajuan Harian', 'Bahasa Melayu': 'Kemajuan Harian', বাংলা: 'দৈনিক অগ্রগতি', தமிழ்: 'தினசரி முன்னேற்றம்', Filipino: 'Daily Progress' 
  },
  remaining: { 
    English: 'kcal remaining', Español: 'kcal restantes', Français: 'kcal restantes', Deutsch: 'kcal übrig', हिन्दी: 'किलो कैलोरी शेष', اردو: 'کیلوری باقی ہے', العربية: 'سعرة متبقية', 中文: '千卡剩余', 日本語: 'kcal 残り', Português: 'kcal restantes', 한국어: 'kcal 남음', Türkçe: 'kcal kaldı', Русский: 'ккал осталось', Italiano: 'kcal rimanenti', Nederlands: 'kcal over', Polski: 'pozostało kcal', Svenska: 'kcal kvar', ไทย: 'แคลอรี่ที่เหลือ', 'Tiếng Việt': 'kcal còn lại', 'Bahasa Indonesia': 'kkal tersisa', 'Bahasa Melayu': 'kkal tersisa', বাংলা: 'কিলোক্যালরি বাকি', தமிழ்: 'மீதமுள்ள கிலோ கலோரி', Filipino: 'kcal remaining' 
  },
  goalReached: { 
    English: 'Goal reached!', Español: '¡Objetivo alcanzado!', Français: 'Objectif atteint!', Deutsch: 'Ziel erreicht!', हिन्दी: 'लक्ष्य प्राप्त!', اردو: 'مقصد حاصل ہو گیا!', العربية: 'تم الوصول للهدف!', 中文: '达成目标！', 日本語: '目標達成！', Português: 'Meta atingida!', 한국어: '목표 달성!', Türkçe: 'Hedefe ulaşıldı!', Русский: 'Цель достигнута!', Italiano: 'Obiettivo raggiunto!', Nederlands: 'Doel bereikt!', Polski: 'Cel osiągnięty!', Svenska: 'Målet nått!', ไทย: 'บรรลุเป้าหมายแล้ว!', 'Tiếng Việt': 'Đạt được mục tiêu!', 'Bahasa Indonesia': 'Target tercapai!', 'Bahasa Melayu': 'Matlamat dicapai!', বাংলা: 'লক্ষ্যে পৌঁছে গেছেন!', தமிழ்: 'இலக்கை எட்டியாச்சு!', Filipino: 'Goal reached!' 
  },
  protein: { English: 'Protein', Español: 'Proteína', Français: 'Protéine', Deutsch: 'Protein', हिन्दी: 'प्रोटीन', اردو: 'پروٹین', العربية: 'بروتين', 中文: '蛋白质', 日本語: 'タンパク質', Português: 'Proteína', 한국어: '단백질', Türkçe: 'Protein', Русский: 'Белок', Italiano: 'Proteine', Nederlands: 'Eiwit', Polski: 'Białko', Svenska: 'Protein', ไทย: 'โปรตีน', 'Tiếng Việt': 'Chất đạm', 'Bahasa Indonesia': 'Protein', 'Bahasa Melayu': 'Protein', বাংলা: 'প্রোটিন', தமிழ்: 'புரதம்', Filipino: 'Protina' },
  carbs: { English: 'Carbs', Español: 'Carbohidratos', Français: 'Glucides', Deutsch: 'Kohlenhydrate', हिन्दी: 'कार्ब्स', اردو: 'کاربوہائیڈریٹ', العربية: 'كربوهيدرات', 中文: '碳水化合物', 日本語: '炭水化物', Português: 'Carboidratos', 한국어: '탄수화물', Türkçe: 'Karbonhidrat', Русский: 'Углеводы', Italiano: 'Carboidrati', Nederlands: 'Koolhydraten', Polski: 'Węglowodany', Svenska: 'Kolhydrater', ไทย: 'คาร์โบไฮเดรต', 'Tiếng Việt': 'Carb', 'Bahasa Indonesia': 'Karbohidrat', 'Bahasa Melayu': 'Karbohidrat', বাংলা: 'কার্বোহাইড্রেট', தமிழ்: 'கார்போஹைட்ரேட்டுகள்', Filipino: 'Carbs' },
  fat: { English: 'Fat', Español: 'Grasa', Français: 'Graisse', Deutsch: 'Fett', हिन्दी: 'वसा', اردو: 'چربی', العربية: 'دهون', 中文: '脂肪', 日本語: '脂質', Português: 'Gordura', 한국어: '지방', Türkçe: 'Yağ', Русский: 'Жир', Italiano: 'Grassi', Nederlands: 'Vet', Polski: 'Tłuszcz', Svenska: 'Fett', ไทย: 'ไขมัน', 'Tiếng Việt': 'Chất béo', 'Bahasa Indonesia': 'Lemak', 'Bahasa Melayu': 'Lemak', বাংলা: 'চর্বি', தமிழ்: 'கொழுப்பு', Filipino: 'Taba' },
  todaysMeals: { English: "Today's Meals", Español: 'Comidas de hoy', Français: "Repas d'aujourd'hui", Deutsch: 'Heutige Mahlzeiten', हिन्दी: 'आज का भोजन', اردو: 'آج کا کھانا', العربية: 'وجبات اليوم', 中文: '今日餐食', 日本語: '今日の食事', Português: 'Refeições de hoje', 한국어: '오늘의 식사', Türkçe: 'Bugünkü Öğünler', Русский: 'Сегодняшние приемы пищи', Italiano: 'Pasti di oggi', Nederlands: 'Maaltijden van vandaag', Polski: 'Dzisiejsze posiłki', Svenska: 'Dagens måltider', ไทย: 'มื้ออาหารวันนี้', 'Tiếng Việt': 'Bữa ăn hôm nay', 'Bahasa Indonesia': 'Makanan Hari Ini', 'Bahasa Melayu': 'Makanan Hari Ini', বাংলা: 'আজকের খাবার', தமிழ்: 'இன்றைய உணவுகள்', Filipino: 'Mga Pagkain Ngayon' },
  noMeals: { 
    English: 'No meals logged yet', Español: 'Aún no hay comidas registradas', Français: 'Aucun repas enregistré', Deutsch: 'Noch keine Mahlzeiten protokolliert', हिन्दी: 'अभी तक कोई भोजन लॉग नहीं किया गया', اردو: 'ابھی تک کوئی کھانا درج नहीं किया गया', العربية: 'لا توجد وجبات مسجلة बाद', 中文: '尚无用膳记录', 日本語: '食事の記録はまだありません', Português: 'Sem refeições registadas', 한국어: '기록된 식사가 없습니다', Türkçe: 'Henüz öğün kaydedilmedi', Русский: 'Пока нет записей о еде', Italiano: 'Nessun pasto registrato', Nederlands: 'Nog geen maaltijden gelogd', Polski: 'Brak zalogowanych posiłków', Svenska: 'Inga måltider loggade än', ไทย: 'ยังไม่มีการบันทึกมื้ออาหาร', 'Tiếng Việt': 'Chưa có bữa ăn nào được ghi lại', 'Bahasa Indonesia': 'Belum ada makanan yang dicatat', 'Bahasa Melayu': 'Belum ada makanan direkodkan', বাংলা: 'এখনও কোনো খাবার লগ করা হয়নি', தமிழ்: 'உணவு எதுவும் பதிவு செய்யப்படவில்லை', Filipino: 'Wala pang nakatalang pagkain' 
  },
  signOut: { 
    English: 'Sign Out', Español: 'Cerrar sesión', Français: 'Déconnexion', Deutsch: 'Abmelden', हिन्दी: 'साइन आउट', اردو: 'سائن آؤٹ', العربية: 'تسجيل الخروج', 中文: '退出登录', 日本語: 'サインアウト', Português: 'Sair', 한국어: '로그아웃', Türkçe: 'Çıkış Yap', Русский: 'Выйти', Italiano: 'Esci', Nederlands: 'Afmelden', Polski: 'Wyloguj się', Svenska: 'Logga ut', ไทย: 'ออกจากระบบ', 'Tiếng Việt': 'Đăng xuất', 'Bahasa Indonesia': 'Keluar', 'Bahasa Melayu': 'Log Keluar', বাংলা: 'সাইন আউট', தமிழ்: 'வெளியேறு', Filipino: 'Sign Out' 
  },
  deleteAccount: { 
    English: 'Delete Account', Español: 'Eliminar cuenta', Français: 'Supprimer le compte', Deutsch: 'Konto löschen', हिन्दी: 'अकाउंट हटाए', اردو: 'اکاؤنٹ حذف کریں', العربية: 'حذف الحساب', 中文: '注销账户', 日本語: 'アカウントを削除', Português: 'Eliminar conta', 한국어: '계정 삭제', Türkçe: 'Hesabı Sil', Русский: 'Удалить аккаунт', Italiano: 'Elimina account', Nederlands: 'Account verwijderen', Polski: 'Usuń konto', Svenska: 'Radera konto', ไทย: 'ลบบัญชี', 'Tiếng Việt': 'Xóa tài khoản', 'Bahasa Indonesia': 'Hapus Akun', 'Bahasa Melayu': 'Padam Akaun', বাংলা: 'অ্যাকাউন্ট মুছুন', தமிழ்: 'கணக்கை நீக்கு', Filipino: 'Delete Account' 
  },
  weeklyPlan: { English: 'Weekly Plan', Español: 'Plan Semanal', Français: 'Plan Hebdomadaire', Deutsch: 'Wochenplan', हिन्दी: 'साप्ताहिक योजना', اردو: 'ہفتہ وار منصوبہ', العربية: 'الخطة الأسبوعية', 中文: '每周计划', 日本語: '週間プラン', Português: 'Plano Semanal', 한국어: '주간 계획', Türkçe: 'Haftalık Plan', Русский: 'Еженедельный план', Italiano: 'Piano settimanale', Nederlands: 'Weekplan', Polski: 'Plan tygodniowy', Svenska: 'Veckoplan', ไทย: 'แผนรายสัปดาห์', 'Tiếng Việt': 'Kế hoạch hàng tuần', 'Bahasa Indonesia': 'Rencana Mingguan', 'Bahasa Melayu': 'Rancangan Mingguan', বাংলা: 'সাপ্তাহিক পরিকল্পনা', தமிழ்: 'வாராந்திர திட்டம்', Filipino: 'Lingguhang Plano' },
  weeklyDesc: { English: 'Tailored to your mood and habits.', Español: 'Adaptado a tu estado de ánimo y hábitos.', Français: 'Adapté à votre humeur et à vos habitudes.', Deutsch: 'Abgestimmt auf Ihre Stimmung und Gewohnheiten.', हिन्दी: 'आपके मूड और आदतों के अनुकूल।', اردو: 'آپ کے موڈ اور عادات کے مطابق۔', العربية: 'مصممة لتناسب مزاجك وعاداتك.', 中文: '根据您的情绪和习惯量身定制。', 日本語: '気分や習慣に合わせて調整。', Português: 'Adaptado ao seu humor e hábitos.', 한국어: '기분과 습관에 맞춤화됨.', Türkçe: 'Ruh halinize ve alışkanlıklarınıza göre tasarlandı.', Русский: 'С учетом вашего настроения и привычек.', Italiano: 'Su misura per il tuo umore e le tue abitudini.', Nederlands: 'Aangepast aan je stemming en gewoontes.', Polski: 'Dostosowane do Twojego nastroju i nawyków.', Svenska: 'Skräddarsytt efter ditt humör och dina vanor.', ไทย: 'ปรับให้เข้ากับอารมณ์และนิสัยของคุณ', 'Tiếng Việt': 'Phù hợp với tâm trạng và thói quen của bạn.', 'Bahasa Indonesia': 'Disesuaikan dengan suasana hati dan kebiasaan Anda.', 'Bahasa Melayu': 'Disesuaikan dengan mood dan tabiat anda.', বাংলা: 'আপনার মেজাজ এবং অভ্যাসের অনুসারে।', தமிழ்: 'உங்கள் மனநிலை மற்றும் பழக்கங்களுக்கு ஏற்ப வடிவமைக்கப்பட்டுள்ளது.', Filipino: 'Ginawa para sa iyong mood at gawi.' },
  swap: { English: 'Swap', Español: 'Cambiar', Français: 'Échanger', Deutsch: 'Austauschen', हिन्दी: 'बदलें', اردو: 'تبدیل کریں', العربية: 'تبديل', 中文: '交换', 日本語: '交換', Português: 'Trocar', 한국어: '교환', Türkçe: 'Değiştir', Русский: 'Заменить', Italiano: 'Scambia', Nederlands: 'Ruilen', Polski: 'Zamień', Svenska: 'Byt', ไทย: 'สลับ', 'Tiếng Việt': 'Hoán đổi', 'Bahasa Indonesia': 'Tukar', 'Bahasa Melayu': 'Tukar', বাংলা: 'অদলবদল', தமிழ்: 'மாற்று', Filipino: 'Palitan' },
  genPlan: { English: 'Generate New Plan', Español: 'Generar nuevo plan', Français: 'Générer un nouveau plan', Deutsch: 'Neuen Plan erstellen', हिन्दी: 'नई योजना बनाएं', اردو: 'نیا منصوبہ بنائیں', العربية: 'إنشاء خطة جديدة', 中文: '生成新计划', 日本語: '新しいプランを作成', Português: 'Gerar Novo Plano', 한국어: '새 계획 생성', Türkçe: 'Yeni Plan Oluştur', Русский: 'Создать новый план', Italiano: 'Genera nuovo piano', Nederlands: 'Nieuw plan genereren', Polski: 'Generuj nowy plan', Svenska: 'Skapa ny plan', ไทย: 'สร้างแผนใหม่', 'Tiếng Việt': 'Tạo kế hoạch mới', 'Bahasa Indonesia': 'Buat Rencana Baru', 'Bahasa Melayu': 'Jana Rancangan Baru', বাংলা: 'নতুন পরিকল্পনা তৈরি করুন', தமிழ்: 'புதிய திட்டத்தை உருவாக்கு', Filipino: 'Gumawa ng Bagong Plano' },
  
  // Paywall Strings
  unlockLimitlessHealth: { English: 'Unlock Limitless Health', Español: 'Desbloquear salud ilimitada', Français: 'Débloquer une santé illimitée', Português: 'Desbloquear saúde ilimitada' },
  paywallDesc: { English: 'Master your habits with AI-powered vision, limitless coaching, and advanced mood tracking.', Español: 'Domina tus hábitos con visión AI, coaching ilimitado y seguimiento avanzado de estado de ánimo.', Français: 'Maîtrisez vos habitudes avec la vision IA, un coaching illimité et un suivi avancé de lhumeur.', Português: 'Domine seus hábitos com visão de IA, coaching ilimitado e rastreamento avançado de humor.' },
  premiumPlan: { English: 'Premium Plan', Español: 'Plan Premium', Français: 'Plan Premium', Português: 'Plano Premium' },
  ultimate: { English: 'Ultimate', Español: 'Último', Français: 'Ultime', Português: 'O melhor' },
  includesTrial: { English: 'Includes 1-Month Free Trial', Español: 'Incluye 1 mes de prueba gratis', Français: 'Comprend 1 mois dessai gratuit', Português: 'Inclui 1 mês de teste grátis' },
  perMonth: { English: '/ month', Español: '/ mes', Français: '/ mois', Português: '/ mês' },
  advancedCamera: { English: 'Advanced Camera AI (Log by snapping photo)', Español: 'Cámara con IA avanzada', Français: 'Caméra IA avancée', Português: 'Câmera com IA avançada' },
  priorityReponses: { English: 'Lightning-fast Priority AI Responses', Español: 'Respuestas de IA más rápidas', Français: 'Réponses plus rapides de lIA', Português: 'Respostas de IA mais rápidas' },
  standardIncludes: { English: 'Everything in Standard included', Español: 'Todo lo del plan Estándar incluido', Français: 'Tout ce qui est dans Standard est inclus', Português: 'Tudo no Standard incluído' },
  standardPlan: { English: 'Standard', Español: 'Estándar', Français: 'Standard', Português: 'Padrão' },
  selected: { English: 'Selected', Español: 'Seleccionado', Français: 'Sélectionné', Português: 'Selecionado' },
  unlimitedChats: { English: 'Unlimited AI Coach Chats', Español: 'Chats ilimitados con el Coach de IA', Français: 'Discussions illimitées avec le coach IA', Português: 'Chats ilimitados com o Coach de IA' },
  unlimitedLogs: { English: 'Unlimited Daily Meal Logs', Español: 'Registros ilimitados de comidas', Français: 'Journaux de repas quotidiens illimités', Português: 'Registros ilimitados de refeições diárias' },
  advancedMood: { English: 'Advanced Mood Correlation Tracking', Español: 'Seguimiento de correlación de estado de ánimo', Français: 'Suivi de la corrélation de lhumeur', Português: 'Rastreamento de correlação de humor ' },
  basicPlan: { English: 'Basic Plan', Español: 'Plan Básico', Français: 'Plan de Base', Português: 'Plano Básico' },
  essentialTracking: { English: 'Essential tracking for starters', Español: 'Seguimiento esencial para principiantes', Français: 'Suivi essentiel pour les débutants', Português: 'Acompanhamento essencial para iniciantes' },
  free: { English: 'Free', Español: 'Gratis', Français: 'Gratuit', Português: 'Livre' },
  chats5: { English: '5 Daily AI Chats', Español: '5 chats de IA diarios', Français: '5 Discussions intelligentes par jour', Português: '5 Chats de IA diários' },
  logs5: { English: '5 Daily Meal Logs', Español: '5 registros de comida diarios', Français: '5 Journaux de repas quotidiens', Português: '5 Registros de refeições diárias' },
  aiEthnicity: { English: 'AI 1-click tailored ethnicity meal plans', Español: 'Planes de comidas personalizados según etnia con 1 clic', Français: 'Plans de repas ethniques personnalisés par IA', Português: 'Planos de refeições de etnia adaptados' },
  cancelAnytime: { English: 'Cancel anytime in Google Play settings', Español: 'Cancela en cualquier momento en Google Play', Français: 'Annulez à tout moment', Português: 'Cancele a qualquer momento no Google Play' },
  continueFree: { English: 'Continue with Free Plan', Español: 'Continuar con el plan gratis', Français: 'Continuer avec le plan gratuit', Português: 'Continuar com o plano gratuito' },
  startFreeTrial: { English: 'Start 1-Month Free Trial', Español: 'Comienza tu prueba de 1 mes gratis', Français: 'Commencer un essai gratuit d1 mois', Português: 'Comece a avaliação gratuita de 1 mês' },
  askCoach: { English: 'Ask your nutritionist...', Español: 'Pregúntale a tu nutricionista...', Français: 'Demandez à votre nutritionniste...', Deutsch: 'Fragen Sie Ihren Ernährungsberater...', हिन्दी: 'अपने पोषण विशेषज्ञ से पूछें...', اردو: 'اپنے ماہر غذائیت سے پوچھیں...', العربية: 'اسأل أخصائي التغذية الخاص بك...', 中文: '向您的营养师提问...', 日本語: '栄養士に質問する...', Português: 'Pergunte ao seu nutricionista...', 한국어: '영양사에게 물어보세요...', Türkçe: 'Diyetisyeninize sorun...', Русский: 'Спросите своего диетолога...', Italiano: 'Chiedi al tuo nutrizionista...', Nederlands: 'Vraag het je voedingsdeskundige...', Polski: 'Zapytaj dietetyka...', Svenska: 'Fråga din dietist...', ไทย: 'ถามนักโภชนาการของคุณ...', 'Tiếng Việt': 'Hỏi chuyên gia dinh dưỡng của bạn...', 'Bahasa Indonesia': 'Tanya ahli gizi Anda...', 'Bahasa Melayu': 'Tanya pakar pemakanan anda...', বাংলা: 'আপনার পুষ্টিবিদকে জিজ্ঞাসা করুন...', தமிழ்: 'உங்கள் ஊட்டச்சத்து நிபுணரிடம் கேளுங்கள்...', Filipino: 'Magtanong sa iyong nutritionist...' },
  chatDisclaimer: { English: 'This AI is for coaching purposes and is not medical advice.', Español: 'Esta IA es para fines de entrenamiento y no es un consejo médico.', Français: "Cette IA est à des fins de coaching et n'est pas un conseil médical.", Deutsch: 'Diese KI dient zu Coaching-Zwecken und stellt keine medizinische Beratung dar.', हिन्दी: 'यह एआई कोचिंग के उद्देश्य से है और चिकित्सा सलाह नहीं है।', اردو: 'یہ اے آئی کوچنگ کے مقاصد کے لیے ہے اور طبی مشورہ نہیں ہے۔', العربية: 'هذا الذكاء الاصطناعي لأغراض التدريب وليس نصيحة طبية.', 中文: '此AI仅供辅导用途，并非医疗建议。', 日本語: 'このAIはコーチング目的であり、医学的アドバイスではありません。', Português: 'Esta IA é para fins de coaching e não é aconselhamento médico.', 한국어: '이 AI는 코칭 목적으로 사용되며 의학적 조언이 아닙니다.', Türkçe: 'Bu yapay zeka koçluk amaçlıdır ve tıbbi tavsiye değildir.', Русский: 'Этот ИИ предназначен для коучинга и не является медицинским советом.', Italiano: 'Questa IA è a scopo di coaching e non sostituisce un parere medico.', Nederlands: 'Deze AI is voor coachingdoeleinden en is geen medisch advies.', Polski: 'Ta sztuczna inteligencja służy do celów coachingowych i nie stanowi porady medycznej.', Svenska: 'Denna AI är för coachningssyften och är inte medicinsk rådgivning.', ไทย: 'AI นี้มีไว้เพื่อการฝึกสอนเท่านั้นและไม่ใช่คำแนะนำทางการแพทย์', 'Tiếng Việt': 'AI này dành cho mục đích huấn luyện và không phải là lời khuyên y tế.', 'Bahasa Indonesia': 'AI ini untuk tujuan pelatihan dan bukan saran medis.', 'Bahasa Melayu': 'AI ini untuk tujuan kejurulatihan dan bukan nasihat perubatan.', বাংলা: 'এই এআই কোচিংয়ের উদ্দেশ্যে এবং এটি কোনো চিকিৎসা পরামর্শ নয়।', தமிழ்: 'இந்த AI பயிற்சி நோக்கங்களுக்காக மட்டுமே உள்ளது மற்றும் மருத்துவ ஆலோசனை அல்ல.', Filipino: 'Ang AI na ito ay para sa coaching purposes at hindi medical advice.' },
  onboardingWelcome: { English: 'Welcome to MindfulBite', Español: 'Bienvenido a MindfulBite', Français: 'Bienvenue sur MindfulBite', Deutsch: 'Willkommen bei MindfulBite', हिन्दी: 'माइंडफुलबाइट में आपका स्वागत है', اردو: 'مائنڈفل بائٹ میں خوش آمدید', العربية: 'مرحباً بك في MindfulBite', 中文: '欢迎来到 MindfulBite', 日本語: 'MindfulBiteへようこそ', Português: 'Bem-vindo ao MindfulBite', 한국어: 'MindfulBite 환영합니다', Türkçe: 'MindfulBite\'a Hoş Gediniz', Русский: 'Добро пожаловать в MindfulBite', Italiano: 'Benvenuto in MindfulBite', Nederlands: 'Welkom bij MindfulBite', Polski: 'Witamy w MindfulBite', Svenska: 'Välkommen till MindfulBite', ไทย: 'ยินดีต้อนรับสู่ MindfulBite', 'Tiếng Việt': 'Chào mừng đến MindfulBite', 'Bahasa Indonesia': 'Selamat Datang di MindfulBite', 'Bahasa Melayu': 'Selamat Datang ke MindfulBite', বাংলা: 'মাইনডফুলবাইটে স্বাগতম', தமிழ்: 'MindfulBiteக்கு வருக', Filipino: 'Maligayang pagdating sa MindfulBite' },
  onboardingDesc: { English: 'Tell us a bit about yourself so we can personalize your experience.', Español: 'Cuéntanos un poco sobre ti.', Français: 'Parlez-nous un peu de vous.', Deutsch: 'Erzählen Sie uns ein wenig über sich.', हिन्दी: 'हमें अपने बारे में थोड़ा बताएं।', اردو: 'ہمیں اپنے بارے میں تھوڑا سا بتائیں۔', العربية: 'أخبرنا قليلاً عن نفسك.', 中文: '向我们介绍一下您自己。', 日本語: '少しあなたのことを教えてください。', Português: 'Conte-nos um pouco sobre você.', 한국어: '당신에 대해 조금 알려주세요.', Türkçe: 'Bize biraz kendinizden bahsedin.', Русский: 'Расскажите немного о себе.', Italiano: 'Parlaci un po\' di te.', Nederlands: 'Vertel ons wat over jezelf.', Polski: 'Opowiedz nam trochę o sobie.', Svenska: 'Berätta lite om dig själv.', ไทย: 'บอกเราเกี่ยบกับตัวคุณสักเล็กน้อย', 'Tiếng Việt': 'Hãy cho chúng tôi biết một chút về bạn.', 'Bahasa Indonesia': 'Ceritakan sedikit tentang diri Anda.', 'Bahasa Melayu': 'Beritahu kami sedikit tentang diri anda.', বাংলা: 'আমাদের আপনার সম্পর্কে একটু বলুন।', தமிழ்: 'உங்களைப் பற்றி கொஞ்சம் சொல்லுங்கள்.', Filipino: 'Sabihin sa amin ang ilang bagay tungkol sa iyo.' },
  onboardingFinish: { English: 'Finish Setup', Español: 'Finalizar configuración', Français: 'Terminer la configuration', Deutsch: 'Einrichtung abschließen', हिन्दी: 'सेटअप समाप्त करें', اردو: 'سیٹ اپ مکمل کریں', العربية: 'إنهاء الإعداد', 中文: '完成设置', 日本語: 'セットアップ完了', Português: 'Concluir Configuração', 한국어: '설정 완료', Türkçe: 'Kurulumu Tamamla', Русский: 'Завершить настройку', Italiano: 'Termina configurazione', Nederlands: 'Installatie voltooien', Polski: 'Zakończ konfigurację', Svenska: 'Slutför installation', ไทย: 'เสร็จสิ้นการตั้งค่า', 'Tiếng Việt': 'Hoàn thành cài đặt', 'Bahasa Indonesia': 'Selesaikan Pengaturan', 'Bahasa Melayu': 'Selesai Persediaan', বাংলা: 'সেটআপ শেষ করুন', தமிழ்: 'அமைப்பை முடி', Filipino: 'Tapusin ang Setup' },
  selectLanguage: { English: 'Select Language', Español: 'Seleccionar idioma', Français: 'Choisir la langue', Deutsch: 'Sprache wählen', हिन्दी: 'भाषा चुनें', اردو: 'زبان منتخب کریں', العربية: 'اختر اللغة', 中文: '选择语言', 日本語: '言語を選択', Português: 'Selecionar Idioma', 한국어: '언어 선택', Türkçe: 'Dil Seçin', Русский: 'Выберите язык', Italiano: 'Seleziona lingua', Nederlands: 'Kies taal', Polski: 'Wybierz język', Svenska: 'Välj språk', ไทย: 'เลือกภาษา', 'Tiếng Việt': 'Chọn ngôn ngữ', 'Bahasa Indonesia': 'Pilih Bahasa', 'Bahasa Melayu': 'Pilih Bahasa', বাংলা: 'ভাষা নির্বাচন করুন', தமிழ்: 'மொழியைக் தேர்ந்தெடுக்கவும்', Filipino: 'Pumili ng Wika' },
  yourAICoach: { English: 'Your AI-powered nutrition and mood coach', Español: 'Tu entrenador de nutrición y estado de ánimo impulsado por IA', Français: 'Votre coach nutritionnel et mental alimenté par l\'IA', Deutsch: 'Ihr KI-gestützter Ernährungs- und Stimmungscoach', हिन्दी: 'आपका एआई-संचालित पोषण और मूड कोच', اردو: 'آپ کا اے آئی سے چلنے والا غذائیت اور موڈ کوچ', العربية: 'مدرب التغذية والمزاج الخاص بك المدعوم بالذكاء الاصطناعي', 中文: '您的AI驱动营养和心理状态辅导', 日本語: 'AI搭載の栄養と気分のコーチ', Português: 'Seu coach de nutrição e humor com tecnologia de IA', 한국어: 'AI 기반 영양 및 기분 코치', Türkçe: 'YZ destekli beslenme ve ruh hali koçunuz', Русский: 'Ваш ИИ-тренер по питанию и настроению', Italiano: 'Il tuo coach di nutrizione e umore con intelligenza artificiale', Nederlands: 'Uw AI-aangedreven voeding en stemmingscoach', Polski: 'Twój oparty na sztucznej inteligencji trener odżywiania i nastroju', Svenska: 'Din AI-drivna närings- och stämningscoach', ไทย: 'โค้ชโภชนาการและอารมณ์ของคุณที่ขับเคลื่อนด้วย AI', 'Tiếng Việt': 'Huấn luyện viên dinh dưỡng và tâm trạng do AI hỗ trợ của bạn', 'Bahasa Indonesia': 'Pelatih gizi dan suasana hati Anda yang ditenagai oleh AI', 'Bahasa Melayu': 'Jurulatih pemakanan dan mood anda yang dikuasakan oleh AI', বাংলা: 'আপনার এআই-চালিত পুষ্টি এবং মেজাজ কোচ', தமிழ்: 'உங்கள் AI-சார்ந்த ஊட்டச்சத்து மற்றும் மனநிலை பயிற்சியாளர்', Filipino: 'Ang iyong AI-powered na nutrition at mood coach' },
  emailAddress: { English: 'Email address', Español: 'Correo electrónico', Français: 'Adresse e-mail', Deutsch: 'E-Mail-Adresse', हिन्दी: 'ईमेल पता', اردو: 'ای میل ایڈریس', العربية: 'البريد الإلكتروني', 中文: '电子邮件地址', 日本語: 'メールアドレス', Português: 'Endereço de email', 한국어: '이메일 주소', Türkçe: 'E-posta adresi', Русский: 'Адрес электронной почты', Italiano: 'Indirizzo e-mail', Nederlands: 'E-mailadres', Polski: 'Adres e-mail', Svenska: 'E-postadress', ไทย: 'ที่อยู่อีเมล', 'Tiếng Việt': 'Địa chỉ e-mail', 'Bahasa Indonesia': 'Alamat email', 'Bahasa Melayu': 'Alamat e-mel', বাংলা: 'ইমেইল ঠিকানা', தமிழ்: 'மின்னஞ்சல் முகவரி', Filipino: 'Email address' },
  password: { English: 'Password', Español: 'Contraseña', Français: 'Mot de passe', Deutsch: 'Passwort', हिन्दी: 'पासवर्ड', اردو: 'پاس ورڈ', العربية: 'كلمة المرور', 中文: '密码', 日本語: 'パスワード', Português: 'Senha', 한국어: '비밀번호', Türkçe: 'Şifre', Русский: 'Пароль', Italiano: 'Password', Nederlands: 'Wachtwoord', Polski: 'Hasło', Svenska: 'Lösenord', ไทย: 'รหัสผ่าน', 'Tiếng Việt': 'Mật khẩu', 'Bahasa Indonesia': 'Kata sandi', 'Bahasa Melayu': 'Kata laluan', বাংলা: 'পাসওয়ার্ড', தமிழ்: 'கடவுச்சொல்', Filipino: 'Password' },
  confirmPassword: { English: 'Confirm Password', Español: 'Confirmar contraseña', Français: 'Confirmez le mot de passe', Deutsch: 'Passwort bestätigen', हिन्दी: 'पासवर्ड की पुष्टि करें', اردو: 'پاس ورڈ کی تصدیق کریں', العربية: 'تأكيد كلمة المرور', 中文: '确认密码', 日本語: 'パスワードを確認', Português: 'Confirme a Senha', 한국어: '비밀번호 확인', Türkçe: 'Şifreyi Onayla', Русский: 'Подтвердите пароль', Italiano: 'Conferma password', Nederlands: 'Bevestig wachtwoord', Polski: 'Potwierdź hasło', Svenska: 'Bekräfta lösenord', ไทย: 'ยืนยันรหัสผ่าน', 'Tiếng Việt': 'Xác nhận mật khẩu', 'Bahasa Indonesia': 'Konfirmasi kata sandi', 'Bahasa Melayu': 'Sahkan Kata Laluan', বাংলা: 'পাসওয়ার্ড নিশ্চিত করুন', தமிழ்: 'கடவுச்சொல்லை உறுதியளிக்கவும்', Filipino: 'I-confirm ang Password' },
  signInBtn: { English: 'Sign In', Español: 'Iniciar sesión', Français: 'Se connecter', Deutsch: 'Anmelden', हिन्दी: 'साइन इन करें', اردو: 'سائن ان کریں', العربية: 'تسجيل الدخول', 中文: '登录', 日本語: 'サインイン', Português: 'Entrar', 한국어: '로그인', Türkçe: 'Giriş Yap', Русский: 'Войти', Italiano: 'Accedi', Nederlands: 'Aanmelden', Polski: 'Zaloguj się', Svenska: 'Logga in', ไทย: 'เข้าสู่ระบบ', 'Tiếng Việt': 'Đăng nhập', 'Bahasa Indonesia': 'Masuk', 'Bahasa Melayu': 'Log Masuk', বাংলা: 'সাইন ইন', தமிழ்: 'உள்நுழைக', Filipino: 'Sign In' },
  signUpBtn: { English: 'Sign Up', Español: 'Regístrate', Français: 'S\'inscrire', Deutsch: 'Registrieren', हिन्दी: 'साइन अप करें', اردو: 'سائن اپ کریں', العربية: 'التسجيل', 中文: '注册', 日本語: 'サインアップ', Português: 'Inscreva-se', 한국어: '가입하기', Türkçe: 'Kayıt Ol', Русский: 'Зарегистрироваться', Italiano: 'Iscriviti', Nederlands: 'Aanmelden', Polski: 'Zarejestruj się', Svenska: 'Skapa konto', ไทย: 'ลงทะเบียน', 'Tiếng Việt': 'Đăng ký', 'Bahasa Indonesia': 'Daftar', 'Bahasa Melayu': 'Daftar', বাংলা: 'সাইন আপ', தமிழ்: 'பதிவு செய்ய', Filipino: 'Sign Up' },
  noAccountLabel: { English: 'Don\'t have an account? Sign Up', Español: '¿No tienes cuenta? Regístrate', Français: 'Vous n\'avez pas de compte ? S\'inscrire', Deutsch: 'Noch kein Konto? Registrieren', हिन्दी: 'खाता नहीं है? साइन अप करें', اردو: 'اکاؤنٹ نہیں ہے؟ سائن اپ کریں', العربية: 'ليس لديك حساب؟ التسجيل', 中文: '没有账号？注册', 日本語: 'アカウントをお持ちではありませんか？サインアップ', Português: 'Não tem uma conta? Inscreva-se', 한국어: '계정이 없으신가요? 가입하기', Türkçe: 'Hesabınız yok mu? Kayıt Ol', Русский: 'Нет учетной записи? Зарегистрироваться', Italiano: 'Non hai un account? Iscriviti', Nederlands: 'Nog geen account? Aanmelden', Polski: 'Nie masz konta? Zarejestruj się', Svenska: 'Har du inget konto? Skapa konto', ไทย: 'ไม่มีบัญชี? ลงทะเบียน', 'Tiếng Việt': 'Chưa có tài khoản? Đăng ký', 'Bahasa Indonesia': 'Belum punya akun? Daftar', 'Bahasa Melayu': 'Belum mempunyai akaun? Daftar', বাংলা: 'অ্যাকাউন্ট নেই? সাইন আপ করুন', தமிழ்: 'கணக்கு இல்லையா? பதிவு செய்யவும்', Filipino: 'Walang account? Mag-sign Up' },
  haveAccountLabel: { English: 'Already have an account? Sign In', Español: '¿Ya tienes una cuenta? Iniciar sesión', Français: 'Vous avez déjà un compte ? Se connecter', Deutsch: 'Haben Sie bereits ein Konto? Anmelden', हिन्दी: 'क्या आपके पास पहले से खाता है? साइन इन करें', اردو: 'کیا آپ کا پہلے سے اکاؤنٹ ہے؟ سائن ان کریں', العربية: 'لديك حساب بالفعل؟ تسجيل الدخول', 中文: '已有账号？登录', 日本語: 'すでにアカウントをお持ちですか？サインイン', Português: 'Já tem uma conta? Entrar', 한국어: '이미 계정이 있으신가요? 로그인', Türkçe: 'Zaten hesabınız var mı? Giriş Yap', Русский: 'Уже есть аккаунт? Войти', Italiano: 'Hai già un account? Accedi', Nederlands: 'Heb je al een account? Aanmelden', Polski: 'Masz już konto? Zaloguj się', Svenska: 'Har du redan ett konto? Logga in', ไทย: 'มีบัญชีแล้ว? เข้าสู่ระบบ', 'Tiếng Việt': 'Đã có tài khoản? Đăng nhập', 'Bahasa Indonesia': 'Sudah punya akun? Masuk', 'Bahasa Melayu': 'Sudah mempunyai akaun? Log Masuk', বাংলা: 'ইতোমধ্যে অ্যাকাউন্ট আছে? সাইন ইন করুন', தமிழ்: 'ஏற்கனவே கணக்கு உள்ளதா? உள்நுழையவும்', Filipino: 'Mayroon nang account? Mag-sign In' },
  contGoogle: { English: 'Continue with Google', Español: 'Continuar con Google', Français: 'Continuer avec Google', Deutsch: 'Mit Google fortfahren', हिन्दी: 'Google के साथ जारी रखें', اردو: 'گوگل کے ساتھ جاری رکھیں', العربية: 'المتابعة مع جوجل', 中文: '使用 Google 账号继续', 日本語: 'Google で続行', Português: 'Continuar com o Google', 한국어: 'Google 로 계속', Türkçe: 'Google ile Devam Et', Русский: 'Продолжить с Google', Italiano: 'Continua con Google', Nederlands: 'Doorgaan met Google', Polski: 'Kontynuuj z Google', Svenska: 'Fortsätt med Google', ไทย: 'ดำเนินการต่อด้วย Google', 'Tiếng Việt': 'Tiếp tục với Google', 'Bahasa Indonesia': 'Lanjutkan dengan Google', 'Bahasa Melayu': 'Teruskan dengan Google', বাংলা: 'Google দিয়ে চালিয়ে যান', தமிழ்: 'Google உடன் தொடரவும்', Filipino: 'Magpatuloy gamit ang Google' },
  forgotPassword: { English: 'Forgot Password?', Español: '¿Olvidaste tu contraseña?', Français: 'Mot de passe oublié ?', Deutsch: 'Passwort vergessen?', हिन्दी: 'पासवर्ड भूल गए?', اردو: 'پاسورڈ بھول گئے؟', العربية: 'هل نسيت كلمة المرور؟', 中文: '忘记密码？', 日本語: 'パスワードをお忘れですか？', Português: 'Esqueceu a senha?', 한국어: '비밀번호를 잊으셨나요?', Türkçe: 'Şifrenizi mi unuttunuz?', Русский: 'Забыли пароль?', Italiano: 'Hai dimenticato la password?', Nederlands: 'Wachtwoord vergeten?', Polski: 'Zapomniałeś hasła?', Svenska: 'Glömt lösenordet?', ไทย: 'ลืมรหัสผ่าน?', 'Tiếng Việt': 'Quên mật khẩu?', 'Bahasa Indonesia': 'Lupa Kata Sandi?', 'Bahasa Melayu': 'Lupa Kata Laluan?', বাংলা: 'পাসওয়ার্ড ভুলে গেছেন?', தமிழ்: 'கடவுச்சொல் மறந்துவிட்டதா?', Filipino: 'Nakalimutan ang Password?' },
  resetInstructionsSent: { English: 'Password reset instructions have been sent to your email.', Español: 'Se han enviado las instrucciones de restablecimiento de contraseña a su correo electrónico.', Français: 'Les instructions de réinitialisation ont été envoyées.', Deutsch: 'Die Anweisungen wurden an Ihre E-Mail gesendet.', हिन्दी: 'पासवर्ड रीसेट करने के निर्देश आपके ईमेल पर भेज दिए गए हैं।', اردو: 'پاس ورڈ ری سیٹ کرنے کی ہدایات آپ کے ای میل پر بھیج دی گئی ہیں۔', العربية: 'تم إرسال تعليمات إعادة تعيين كلمة المرور إلى بريدك الإلكتروني.', 中文: '重置密码的说明已发送至您的电子邮箱。', 日本語: 'パスワードリセットの手順がメールで送信されました。', Português: 'As instruções de redefinição de senha foram enviadas para o seu e-mail.', 한국어: '비밀번호 재설정 지침이 이메일로 전송되었습니다.', Türkçe: 'Şifre sıfırlama talimatları e-postanıza gönderildi.', Русский: 'Инструкции по сбросу пароля отправлены на вашу электронную почту.', Italiano: 'Le istruzioni per il reset della password sono state inviate alla tua email.', Nederlands: 'Instructies voor het opnieuw instellen van uw wachtwoord zijn naar uw e-mail verzonden.', Polski: 'Instrukcje resetowania hasła zostały wysłane na podany adres e-mail.', Svenska: 'Instruktioner för lösenordsåterställning har skickats till din e-post.', ไทย: 'คำแนะนำในการรีเซ็ตรหัสผ่านได้ถูกส่งไปยังอีเมลของคุณแล้ว', 'Tiếng Việt': 'Hướng dẫn đặt lại mật khẩu đã được gửi đến email của bạn.', 'Bahasa Indonesia': 'Instruksi reset kata sandi telah dikirim ke email Anda.', 'Bahasa Melayu': 'Arahan tetapan semula kata laluan telah dihantar ke e-mel anda.', বাংলা: 'আপনার ইমেইলে পাসওয়ার্ড রিসেট করার নির্দেশাবলী পাঠানো হয়েছে।', தமிழ்: 'உங்கள் மின்னஞ்சலுக்கு கடவுச்சொல் மாற்றுவதற்கான வழிமுறைகள் அனுப்பப்பட்டுள்ளன.', Filipino: 'Ipinadala na ang instructions para sa password reset sa iyong email.' },
  enterNewPassword: { English: 'Enter New Password', Español: 'Ingrese la nueva contraseña', Français: 'Entrez un nouveau mot de passe', Deutsch: 'Neues Passwort eingeben', हिन्दी: 'नया पासवर्ड दर्ज करें', اردو: 'نیا پاس ورڈ درج کریں', العربية: 'أدخل كلمة المرور الجديدة', 中文: '输入新密码', 日本語: '新しいパスワードを入力', Português: 'Digite a nova senha', 한국어: '새 비밀번호 입력', Türkçe: 'Yeni Şifreyi Girin', Русский: 'Введите новый пароль', Italiano: 'Inserisci nuova password', Nederlands: 'Voer nieuw wachtwoord in', Polski: 'Wprowadź nowe hasło', Svenska: 'Ange nytt lösenord', ไทย: 'ใส่รหัสผ่านใหม่', 'Tiếng Việt': 'Nhập mật khẩu mới', 'Bahasa Indonesia': 'Masukkan Kata Sandi Baru', 'Bahasa Melayu': 'Masukkan Kata Laluan Baru', বাংলা: 'নতুন পাসওয়ার্ড লিখুন', தமிழ்: 'புதிய கடவுச்சொல்லை உள்ளிடவும்', Filipino: 'Ipasok ang Bagong Password' },
  updatePasswordBtn: { English: 'Update Password', Español: 'Actualizar contraseña', Français: 'Mettre à jour', Deutsch: 'Passwort aktualisieren', हिन्दी: 'पासवर्ड अपडेट करें', اردو: 'پاسورڈ اپ ڈیٹ کریں', العربية: 'تحديث كلمة المرور', 中文: '更新密码', 日本語: 'パスワードを更新', Português: 'Atualizar senha', 한국어: '비밀번호 업데이트', Türkçe: 'Şifreyi Güncelle', Русский: 'Обновить пароль', Italiano: 'Aggiorna password', Nederlands: 'Wachtwoord bijwerken', Polski: 'Zaktualizuj hasło', Svenska: 'Uppdatera lösenord', ไทย: 'อัปเดตรหัสผ่าน', 'Tiếng Việt': 'Cập nhật mật khẩu', 'Bahasa Indonesia': 'Perbarui Kata Sandi', 'Bahasa Melayu': 'Kemas kini Kata Laluan', বাংলা: 'পাসওয়ার্ড আপডেট করুন', தமிழ்: 'கடவுச்சொல்லைப் புதுப்பிக்கவும்', Filipino: 'I-update ang Password' }
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('English');

  const t = (key: string) => {
    return translations[key]?.[language] || translations[key]?.['English'] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
